osx_image: xcode8.3
language: objective-c

branches:
  only:
    - master

env:
  - DESTINATION="OS=10.3,name=iPhone 7" SDK=iphonesimulator

script:
- set -o pipefail && xcodebuild -scheme MaskedLabel -sdk "$SDK" -destination "$DESTINATION" | xcpretty
